import "./styles/globals.css";
import { Josefin_Sans } from "next/font/google";
import Head from "next/head";

const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Seguros Mayaluna",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <body className={josefin.className}>{children}</body>
    </html>
  );
}
